### ISSUE TITLE
Directory ./public/-dxdebug.remote_enable=1 does not exist.

### ISSUE THREAD

**Issue by hugot** [tacnoman/dephpugger#15]
When running `dephpugger server` with the following config:

```
debugger: 
  host: mysocket.dev # default: localhost
  port: 9002 # default: 9005
  lineOffset: 10 # default: 6
  verboseMode: false # default: false
  historyFile: ~/.dephpugger_history # default: .dephpugger_history
server:
  host: 127.0.0.1 # default: localhost
  port: 3333 # default: 8888
  path: ./public/  # default: null
  file: app_dev.php # default: null

```

the process exits with the following message: 
```
Directory ./public/-dxdebug.remote_enable=1 does not exist.
```
